version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: zamemo_user
      POSTGRES_PASSWORD: z1a4m4e8t8k!
      POSTGRES_DB: zamemo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: